### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [johnrambow/james-hogg_the-private-memoirs-and-confessions-of-a-justified-sinner#1]
The Editor's Narrative:

- [x] The Editor's Narrative resembles a prologue. The file name needs to be changed to `prologue.xhtml` and the file `<section>` semantics to be `<section id="prologue" epub:type="prologue">`.

The Private Memoirs and Confessions of a Sinner:

- [x] Since The Private Memoirs and Confessions of a Sinner doesn't have any chapters, the file can be named `private-memoirs-and-confessions-of-a-sinner.xhtml` and the file `<section>` semantics can be `<section id="private-memoirs-and-confessions-of-a-sinner" epub:type="division">`

- [x] Re-run `se semanticate .` again and commit the changes.

- [x] "Paulies" can be italicized for the first instance and wrapped in `<span>` for the rest.

- [x] There are some mismatched dashes found.

- [x] The text after "End of the Memoir" is a continuation of the The Editor's Narrative and resembles an epilogue. This can go in an `epilogue.xhtml` file. This file can also be titled The Editor's Narrative for easy navigation.

- [x] Remove "End of the Memoir".

content.opf:

- [x] Add the source link [https://archive.org/details/privatememoirsco00hoggrich](https://archive.org/details/privatememoirsco00hoggrich ).

local.css:

- [x] We avoid using single-use classes for styling. You can target that specific `<blockquote>` with:
`#FILE-ID blockquote:nth-of-type(N){}

**Comment by johnrambow** [comment]
Thanks for looking this over, Emma. I am working on these issues now. 

For adding an additional source link, that means I need to adjust the imprint also, as in [6.4.4.3.2](https://standardebooks.org/manual/1.7.0/single-page#6.4.4.3.2), right? (I read against scans from a 1926 edition (https://catalog.hathitrust.org/Record/000438212), but the illustration comes from the first edition.)

**Comment by EmmaSweeney** [comment]
You will need to adjust both the imprint and colophon. You can add an xml comment ([SEMOS 9.8.3.1](https://standardebooks.org/manual/1.7.0/single-page#9.8.3.1)) in the content.opf for each set of page scans, saying which is the edition read against and which has the illustration.

**Comment by johnrambow** [comment]
EDITED: still working on this -- I messed up content.opf somehow.

**Comment by johnrambow** [comment]
OK, everything should be fixed now, for real. And thanks for your help.
